In [5]:
import numpy as np
import pandas as pd

import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot

from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import networkx as nx

import time

C:\Work\Python\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning:

`should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.

In [6]:
df_fp=pd.read_csv("Bakery.csv")
df_fp.head(10)

C:\Work\Python\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning:

`should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.

   TransactionNo          Items          DateTime  Daypart  DayType
0              1          Bread  30-10-2016 09:58  Morning  Weekend
1              2   Scandinavian  30-10-2016 10:05  Morning  Weekend
2              2   Scandinavian  30-10-2016 10:05  Morning  Weekend
3              3  Hot chocolate  30-10-2016 10:07  Morning  Weekend
4              3            Jam  30-10-2016 10:07  Morning  Weekend
5              3        Cookies  30-10-2016 10:07  Morning  Weekend
6              4         Muffin  30-10-2016 10:08  Morning  Weekend
7              5         Coffee  30-10-2016 10:13  Morning  Weekend
8              5         Pastry  30-10-2016 10:13  Morning  Weekend
9              5          Bread  30-10-2016 10:13  Morning  Weekend

In [7]:
# FP GROWTH

# Selecting the relevant columns

# Grouping items by transaction and converting them into lists
df_fp = df_fp.groupby('TransactionNo')['Items'].apply(list).to_list()

# Instantiate a transaction encoder
transEncoder = TransactionEncoder()

# Fit the transaction encoder using the list of transaction lists
transEncoder.fit(df_fp)

# Transform the list of transaction lists into an array of encoded transactions
enctrans = transEncoder.transform(df_fp)

# Convert the array of encoded transactions into a dataframe
df_fp_final = pd.DataFrame(enctrans, columns=transEncoder.columns_)
df_fp_final.head()

C:\Work\Python\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning:

`should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.

,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
from mlxtend.frequent_patterns.fpgrowth import fpgrowth

# Calculation of Execution time
start_time = time.time()

# List of frequency itemset
frequent_itemsets = fpgrowth(df_fp_final, min_support=0.0001, use_colnames = True)

# Calculate elapsed time
elapsed_time = time.time() - start_time

# Print the elapsed time
print("Elapsed time:", elapsed_time, "seconds")

frequent_itemsets.head(10)

C:\Work\Python\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning:

`should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.

Elapsed time: 0.32383298873901367 seconds

    support         itemsets
0  0.327205          (Bread)
1  0.029054   (Scandinavian)
2  0.058320  (Hot chocolate)
3  0.054411        (Cookies)
4  0.015003            (Jam)
5  0.038457         (Muffin)
6  0.478394         (Coffee)
7  0.086107         (Pastry)
8  0.061807      (Medialuna)
9  0.142631            (Tea)

In [9]:
# compute and print the association rules
from mlxtend.frequent_patterns import association_rules
association_rules(frequent_itemsets, metric="lift", min_threshold=0.5)

C:\Work\Python\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning:

`should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Coffee),(Bread),0.478394,0.327205,0.090016,0.188163,0.575059,-0.066517,0.828731,-0.586210
1,(Bread),(Coffee),0.327205,0.478394,0.090016,0.275105,0.575059,-0.066517,0.719561,-0.523431
2,(Coffee),(Hot chocolate),0.478394,0.058320,0.029583,0.061837,1.060311,0.001683,1.003749,0.109048
3,(Hot chocolate),(Coffee),0.058320,0.478394,0.029583,0.507246,1.060311,0.001683,1.058553,0.060403
4,(Hot chocolate),(Bread),0.058320,0.327205,0.013418,0.230072,0.703144,-0.005665,0.873841,-0.309550
...,...,...,...,...,...,...,...,...,...,...
69,(Toast),(Coffee),0.033597,0.478394,0.023666,0.704403,1.472431,0.007593,1.764582,0.332006
70,(Coffee),(Scone),0.478394,0.034548,0.018067,0.037765,1.093107,0.001539,1.003343,0.163296
71,(Scone),(Coffee),0.034548,0.478394,0.018067,0.522936,1.093107,0.001539,1.093366,0.088224
72,(Coffee),(Spanish Brunch),0.478394,0.018172,0.010882,0.022747,1.251766,0.002189,1.004682,0.385594
73,(Spanish Brunch),(Coffee),0.018172,0.478394,0.010882,0.598837,1.251766,0.002189,1.300235,0.204851